### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by Ale32bit** [Ale32bit/SwitchChat#1]
```
(node:18185) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: NaN
    at onParseError (internal/url.js:240:17)
    at parse (internal/url.js:249:3)
    at new URL (internal/url.js:324:5)
    at WebSocket.initAsClient (/home/ale32bit/switchbot/node_modules/ws/lib/websocket.js:470:27)
    at new WebSocket (/home/ale32bit/switchbot/node_modules/ws/lib/websocket.js:62:20)
    at Promise (/home/ale32bit/switchbot/node_modules/switchchat/src/Client.js:54:23)
    at new Promise (<anonymous>)
    at Timeout.connect [as _onTimeout] (/home/ale32bit/switchbot/node_modules/switchchat/src/Client.js:53:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
(node:18185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18185) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Ale32bit** [comment]
setTimeout set `this` to its scope instead of using Client scope.
Fixed by creating a new arrow function `reconnect` (This way `Client.connect` uses Client scope).
